"""phase 2 3 advanced tables

Revision ID: 5ecccefa9097
Revises: 8b634842cf28
Create Date: 2026-10-05 11:59:26.628640

"""
from alembic import op
import sqlalchemy as sa


revision = '5ecccefa9097'
down_revision = '8b634842cf28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('model_experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_name', sa.String(length=200), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('dataset_version', sa.String(length=40), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('training_duration_seconds', sa.Double(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_experiments_experiment_name'), 'model_experiments', ['experiment_name'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('dataset_version', sa.String(length=40), nullable=False),
    sa.Column('feature_version', sa.String(length=40), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('artifact_location', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_model_type'), 'model_versions', ['model_type'], unique=False)
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_table('batch_prediction_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=True),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_prediction_jobs_requested_by'), 'batch_prediction_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_batch_prediction_jobs_status'), 'batch_prediction_jobs', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index('ix_notifications_recipient_read', 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_table('learning_resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_resources_course_id'), 'learning_resources', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_resources_topic'), 'learning_resources', ['topic'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_course_id'), 'learning_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_session_date'), 'learning_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_learning_sessions_student_id'), 'learning_sessions', ['student_id'], unique=False)
    op.create_index('ix_sessions_student_course_date', 'learning_sessions', ['student_id', 'course_id', 'session_date'], unique=False)
    op.create_table('student_learning_sequences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_date', sa.Date(), nullable=False),
    sa.Column('sequence_data', sa.JSON(), nullable=False),
    sa.Column('sequence_length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sequences_student_course_date', 'student_learning_sequences', ['student_id', 'course_id', 'sequence_date'], unique=False)
    op.create_index(op.f('ix_student_learning_sequences_course_id'), 'student_learning_sequences', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_learning_sequences_student_id'), 'student_learning_sequences', ['student_id'], unique=False)
    op.create_table('faculty_interventions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('prediction_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('intervention_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_interventions_faculty_id'), 'faculty_interventions', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_faculty_interventions_student_id'), 'faculty_interventions', ['student_id'], unique=False)
    op.create_table('prediction_explanations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('feature', sa.String(length=120), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_explanations_prediction_method', 'prediction_explanations', ['prediction_id', 'method'], unique=False)
    op.create_index(op.f('ix_prediction_explanations_prediction_id'), 'prediction_explanations', ['prediction_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=True),
    sa.Column('prediction_id', sa.Uuid(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_course_id'), 'recommendations', ['course_id'], unique=False)
    op.create_index(op.f('ix_recommendations_prediction_id'), 'recommendations', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_recommendations_student_id'), 'recommendations', ['student_id'], unique=False)
    op.create_index('ix_recommendations_student_status', 'recommendations', ['student_id', 'status'], unique=False)
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_feedback_recommendation_id'), 'recommendation_feedback', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_student_id'), 'recommendation_feedback', ['student_id'], unique=False)
    op.add_column('predictions', sa.Column('model_type', sa.String(length=20), server_default='BASELINE', nullable=False))
    op.execute("UPDATE predictions SET model_type = 'BASELINE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'model_type')
    op.drop_index(op.f('ix_recommendation_feedback_student_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_recommendation_id'), table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_index('ix_recommendations_student_status', table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_student_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_prediction_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_course_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_prediction_explanations_prediction_id'), table_name='prediction_explanations')
    op.drop_index('ix_explanations_prediction_method', table_name='prediction_explanations')
    op.drop_table('prediction_explanations')
    op.drop_index(op.f('ix_faculty_interventions_student_id'), table_name='faculty_interventions')
    op.drop_index(op.f('ix_faculty_interventions_faculty_id'), table_name='faculty_interventions')
    op.drop_table('faculty_interventions')
    op.drop_index(op.f('ix_student_learning_sequences_student_id'), table_name='student_learning_sequences')
    op.drop_index(op.f('ix_student_learning_sequences_course_id'), table_name='student_learning_sequences')
    op.drop_index('ix_sequences_student_course_date', table_name='student_learning_sequences')
    op.drop_table('student_learning_sequences')
    op.drop_index('ix_sessions_student_course_date', table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_student_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_session_date'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_course_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_learning_resources_topic'), table_name='learning_resources')
    op.drop_index(op.f('ix_learning_resources_course_id'), table_name='learning_resources')
    op.drop_table('learning_resources')
    op.drop_index('ix_notifications_recipient_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_batch_prediction_jobs_status'), table_name='batch_prediction_jobs')
    op.drop_index(op.f('ix_batch_prediction_jobs_requested_by'), table_name='batch_prediction_jobs')
    op.drop_table('batch_prediction_jobs')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_type'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_model_experiments_experiment_name'), table_name='model_experiments')
    op.drop_table('model_experiments')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
